# Importing Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)
# or we can specify our data type
c = np.array([1,2,3], dtype= 'int16')

[1 2 3]


# 2D

In [3]:
b = np.array([[2.1,3.0,2.0],[1.0,2.0,3.0]])
print(b)

[[2.1 3.  2. ]
 [1.  2.  3. ]]


In [4]:
# get the Dimension of array
b.ndim

2

In [5]:
a.ndim

1

In [6]:
# get the shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
# get Type
a.dtype

dtype('int32')

In [8]:
c.dtype

dtype('int16')

In [9]:
#Get size mean the bytes size of each element in array
a.itemsize

4

In [10]:
c.itemsize

2

In [11]:
# size of array (total length of array)
print(a.size)
print(b.size)

3
6


In [12]:
# get total byte size of array
print(a.nbytes)

# float is 8 bytes so 8*6 = 48
print(b.nbytes)


12
48


# Accessing or Changing Specific element, row, columns, etc...

In [17]:
array_1 = np.array([[1,2,3,4,5,6,7],[13,14,15,16,17,18,19]])
print(array_1)

[[ 1  2  3  4  5  6  7]
 [13 14 15 16 17 18 19]]


In [15]:
array_1.shape

(2, 7)

In [18]:
# Get a specific element [r,c]
# Get a specific index 
# I want to get 18 from array
# As array index start from 0
array_1[1, 5]

18

In [19]:
# We can use the negatve notation also
# now we want to acces the 17
array_1[1, -3]

17

In [20]:
# Get a specific row
array_1[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
# Get a Specific Column
array_1[:,2]

array([ 3, 15])

In [28]:
# Getting a litte more fancy[startindex:endindex]
array_1[0, 0:3]

array([1, 2, 3])

In [27]:
# Getting a litte more fancy[startindex:endindex:stepsize]
array_1[0, 0:6:2]

array([1, 3, 5])

In [30]:
# we also do negative
# Getting a litte more fancy[startindex:endindex]
array_1[0, 0:-3]

array([1, 2, 3, 4])

In [31]:
# Changing the specific number
# Let we need to change the 7
print(array_1)
print('/////////////')
array_1[0,6] = 25
print(array_1)

[[ 1  2  3  4  5  6  7]
 [13 14 15 16 17 18 19]]
/////////////
[[ 1  2  3  4  5  6 25]
 [13 14 15 16 17 18 19]]


In [32]:
# Changing the specific number in column
array_1[: , 2] = 29
print(array_1)

[[ 1  2 29  4  5  6 25]
 [13 14 29 16 17 18 19]]


In [33]:
array_1[: , 3] = [44,45]
print(array_1)

[[ 1  2 29 44  5  6 25]
 [13 14 29 45 17 18 19]]
